const tiles = [
    { name: "Go", color: "none", x: 10, y: 10 },
    { name: "Old Kent Road", color: "brown", x: 9, y: 10 }, 
    { name: "Community Chest", color: "none", x: 8, y: 10 },
    { name: "Whitechapel Road", color: "brown", x: 7, y: 10 }, 
    { name: "Income Tax", color: "none", x: 6, y: 10 },
    { name: "Kings Cross Station", color: "station", x: 5, y: 10 }, 
    { name: "The Angel Islington", color: "light-blue", x: 4, y: 10 },
    { name: "Chance", color: "none", x: 3, y: 10 },
    { name: "Euston Road", color: "light-blue", x: 2, y: 10 },
    { name: "Pentonville Road", color: "light-blue", x: 1, y: 10 },
    { name: "Jail", color: "none", x: 0, y: 10 },
    { name: "Pall Mall", color: "pink", x: 0, y: 9 },
    { name: "Electric Company", color: "utility", x: 0, y: 8 },
    { name: "Whitehall", color: "pink", x: 0, y: 7 },
    { name: "Northumberland Avenue", color: "pink", x: 0, y: 6 },
    { name: "Marylebone Station", color: "station", x: 0, y: 5 },
    { name: "Bow Street", color: "orange", x: 0, y: 4 },
    { name: "Community Chest", color: "none", x: 0, y: 3 },
    { name: "Marlborough Street", color: "orange", x: 0, y: 2 },
    { name: "Vine Street", color: "orange", x: 0, y: 1 },
    { name: "Free Parking", color: "none", x: 0, y: 0 },
    { name: "Strand", color: "red", x: 1, y: 0 },
    { name: "Chance", color: "none", x: 2, y: 0 },
    { name: "Fleet Street", color: "red", x: 3, y: 0 },
    { name: "Trafalgar Square", color: "red", x: 4, y: 0 },
    { name: "Fenchurch St Station", color: "station", x: 5, y: 0 },
    { name: "Leicester Square", color: "yellow", x: 6, y: 0 },
    { name: "Coventry Street", color: "yellow", x: 7, y: 0 },
    { name: "Water Works", color: "utility", x: 8, y: 0 },
    { name: "Piccadilly", color: "yellow", x: 9, y: 0 },
    { name: "Go to Jail", color: "none", x: 10, y: 0 },
    { name: "Regent Street", color: "green", x: 10, y: 1 },
    { name: "Oxford Street", color: "green", x: 10, y: 2 },
    { name: "Community Chest", color: "none", x: 10, y: 3 },
    { name: "Bond Street", color: "green", x: 10, y: 4 },
    { name: "Liverpool St Station", color: "station", x: 10, y: 5 },
    { name: "Chance", color: "none", x: 10, y: 6 },
    { name: "Park Lane", color: "blue", x: 10, y: 7 },
    { name: "Super Tax", color: "none", x: 10, y: 8 },
    { name: "Mayfair", color: "blue", x: 10, y: 9 }
];